jwt:
  secret: keqoeurpqieurpqemvzlkdfkqerpqieuria45eqkrekqmlradfadfaef

server:
  port: 0

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/AnimalWar?serverTimezone=Asia/Seoul
    username: root
    password: 1q2w3e4r
#  spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.MySQLDialect
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
