package com.example.aniamlwaruser.service;


import com.example.aniamlwaruser.domain.entity.*;
import com.example.aniamlwaruser.repository.AnimalINVTRepository;
import com.example.aniamlwaruser.repository.AnimalRepository;
import com.example.aniamlwaruser.repository.UserRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.context.annotation.Bean;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;

import java.util.List;

@Service
@RequiredArgsConstructor
public class AnimalService {
    private final AnimalRepository animalRepository;
    private final AnimalINVTRepository animalINVTRepository;
    private final UserRepository userRepository;
    private final PasswordEncoder passwordEncoder;
    @Bean
    public ResponseEntity<String> saveAnimals() {
        // buildingRepository 비어 있으면 저장
        if (!animalRepository.findAll().isEmpty()) {
            return ResponseEntity.status(HttpStatus.CONFLICT)
                    .body("Data already exists");
        }

        // 데이터 저장 로직 추가 (이 부분은 생략된 것으로 가정)

        // animalRepository가 비어 있을 때만 저장
        if (animalRepository.findAll().isEmpty()) {
            animalRepository.saveAll(List.of(
                    Animal.builder()
                            .name("말티즈")
                            .grade(Grade.NORMAL)
                            .attackPower(20)
                            .defencePower(12)
                            .life(85)
                            .species(Species.DOG)
                            .imagePath("Maltese.webp")
                            .build(),
                    Animal.builder()
                            .name("시츄")
                            .grade(Grade.NORMAL)
                            .attackPower(22)
                            .defencePower(14)
                            .life(90)
                            .species(Species.DOG)
                            .imagePath("Shihtzu.webp")
                            .build(),
                    Animal.builder()
                            .name("요크셔테리어")
                            .grade(Grade.NORMAL)
                            .attackPower(25)
                            .defencePower(15)
                            .life(88)
                            .species(Species.DOG)
                            .imagePath("WelshTerrier.webp")
                            .build(),
                    Animal.builder()
                            .name("비글")
                            .grade(Grade.NORMAL)
                            .attackPower(22)
                            .defencePower(14)
                            .life(95)
                            .species(Species.DOG)
                            .imagePath("Beagle.webp")
                            .build(),
                    Animal.builder()
                            .name("치와와")
                            .grade(Grade.NORMAL)
                            .attackPower(12)
                            .defencePower(8)
                            .life(75)
                            .species(Species.DOG)
                            .imagePath("Chihuahua.webp")
                            .build(),
                    Animal.builder()
                            .name("푸들")
                            .grade(Grade.NORMAL)
                            .attackPower(17)
                            .defencePower(11)
                            .life(85)
                            .species(Species.DOG)
                            .imagePath("Poodle.webp")
                            .build(),
                    Animal.builder()
                            .name("포메라니언")
                            .grade(Grade.NORMAL)
                            .attackPower(14)
                            .defencePower(9)
                            .life(75)
                            .species(Species.DOG)
                            .imagePath("Pomeranian.webp")
                            .build(),
                    Animal.builder()
                            .name("퍼그")
                            .grade(Grade.NORMAL)
                            .attackPower(19)
                            .defencePower(13)
                            .life(90)
                            .species(Species.DOG)
                            .imagePath("Pug.webp")
                            .build(),
                    Animal.builder()
                            .name("닥스훈트")
                            .grade(Grade.NORMAL)
                            .attackPower(21)
                            .defencePower(16)
                            .life(88)
                            .species(Species.DOG)
                            .imagePath("Dachshund.webp")
                            .build(),
                    Animal.builder()
                            .name("프렌치불독")
                            .grade(Grade.NORMAL)
                            .attackPower(25)
                            .defencePower(20)
                            .life(95)
                            .species(Species.DOG)
                            .imagePath("FrenchBulldog.webp")
                            .build(),
                    Animal.builder()
                            .name("너구리")
                            .grade(Grade.NORMAL)
                            .attackPower(10)
                            .defencePower(5)
                            .life(50)
                            .species(Species.DOG)
                            .imagePath("Raccoon.webp")
                            .build(),
                    Animal.builder()
                            .name("여우")
                            .grade(Grade.NORMAL)
                            .attackPower(12)
                            .defencePower(7)
                            .life(60)
                            .species(Species.DOG)
                            .imagePath("Fox.webp")
                            .build(),
                    Animal.builder()
                            .name("덤불개")
                            .grade(Grade.NORMAL)
                            .attackPower(20)
                            .defencePower(15)
                            .life(100)
                            .species(Species.DOG)
                            .imagePath("BushDog.webp")
                            .build(),
                    Animal.builder()
                            .name("시바")
                            .grade(Grade.NORMAL)
                            .attackPower(24)
                            .defencePower(18)
                            .life(95)
                            .species(Species.DOG)
                            .imagePath("ShibaInu.webp")
                            .build(),
                    Animal.builder()
                            .name("그레이하운드")
                            .grade(Grade.NORMAL)
                            .attackPower(26)
                            .defencePower(22)
                            .life(90)
                            .species(Species.DOG)
                            .imagePath("Greyhound.webp")
                            .build(),
                    Animal.builder()
                            .name("승냥이")
                            .grade(Grade.NORMAL)
                            .attackPower(30)
                            .defencePower(30)
                            .life(100)
                            .species(Species.DOG)
                            .imagePath("AsiaticWildDog.webp")
                            .build(),
                    Animal.builder()
                            .name("보더콜리")
                            .grade(Grade.NORMAL)
                            .attackPower(23)
                            .defencePower(19)
                            .life(88)
                            .species(Species.DOG)
                            .imagePath("BorderCollie.webp")
                            .build(),
                    Animal.builder()
                            .name("웰시테리어")
                            .grade(Grade.NORMAL)
                            .attackPower(16)
                            .defencePower(11)
                            .life(80)
                            .species(Species.DOG)
                            .imagePath("WelshTerrier.webp")
                            .build(),
                    Animal.builder()
                            .name("코커스파니엘")
                            .grade(Grade.NORMAL)
                            .attackPower(19)
                            .defencePower(14)
                            .life(85)
                            .species(Species.DOG)
                            .imagePath("CockerSpaniel.webp")
                            .build(),
                    Animal.builder()
                            .name("불테리어")
                            .grade(Grade.NORMAL)
                            .attackPower(24)
                            .defencePower(20)
                            .life(90)
                            .species(Species.DOG)
                            .imagePath("BullTerrier.webp")
                            .build(),
                    Animal.builder()
                            .name("슈나우져")
                            .grade(Grade.NORMAL)
                            .attackPower(27)
                            .defencePower(25)
                            .life(95)
                            .species(Species.DOG)
                            .imagePath("Schnauzer.webp")
                            .build(),
                    Animal.builder()
                            .name("말티푸")
                            .grade(Grade.NORMAL)
                            .attackPower(16)
                            .defencePower(12)
                            .life(85)
                            .species(Species.DOG)
                            .imagePath("Maltipoo.webp")
                            .build(),
                    Animal.builder()
                            .name("도베르만")
                            .grade(Grade.RARE)
                            .attackPower(45)
                            .defencePower(45)
                            .life(160)
                            .species(Species.DOG)
                            .imagePath("Doberman.webp")
                            .build(),
                    Animal.builder()
                            .name("셰퍼드")
                            .grade(Grade.RARE)
                            .attackPower(48)
                            .defencePower(48)
                            .life(170)
                            .species(Species.DOG)
                            .imagePath("Shepherd.webp")
                            .build(),
                    Animal.builder()
                            .name("불도그")
                            .grade(Grade.RARE)
                            .attackPower(50)
                            .defencePower(50)
                            .life(180)
                            .species(Species.DOG)
                            .imagePath("Bulldog.webp")
                            .build(),
                    Animal.builder()
                            .name("말라뮤트")
                            .grade(Grade.RARE)
                            .attackPower(49)
                            .defencePower(49)
                            .life(175)
                            .species(Species.DOG)
                            .imagePath("Malamute.webp")
                            .build(),
                    Animal.builder()
                            .name("허스키")
                            .grade(Grade.RARE)
                            .attackPower(47)
                            .defencePower(47)
                            .life(170)
                            .species(Species.DOG)
                            .imagePath("Husky.webp")
                            .build(),
                    Animal.builder()
                            .name("늑대")
                            .grade(Grade.RARE)
                            .attackPower(46)
                            .defencePower(46)
                            .life(165)
                            .species(Species.DOG)
                            .imagePath("Wolf.webp")
                            .build(),
                    Animal.builder()
                            .name("자칼")
                            .grade(Grade.RARE)
                            .attackPower(44)
                            .defencePower(44)
                            .life(160)
                            .species(Species.DOG)
                            .imagePath("Jackal.webp")
                            .build(),
                    Animal.builder()
                            .name("리트리버")
                            .grade(Grade.RARE)
                            .attackPower(49)
                            .defencePower(49)
                            .life(175)
                            .species(Species.DOG)
                            .imagePath("Retriever.webp")
                            .build(),
                    Animal.builder()
                            .name("사모예드")
                            .grade(Grade.RARE)
                            .attackPower(48)
                            .defencePower(48)
                            .life(170)
                            .species(Species.DOG)
                            .imagePath("Samoyed.webp")
                            .build(),
                    Animal.builder()
                            .name("살루키")
                            .grade(Grade.RARE)
                            .attackPower(47)
                            .defencePower(47)
                            .life(165)
                            .species(Species.DOG)
                            .imagePath("Saluki.webp")
                            .build(),
                    Animal.builder()
                            .name("달마시안")
                            .grade(Grade.RARE)
                            .attackPower(46)
                            .defencePower(46)
                            .life(160)
                            .species(Species.DOG)
                            .imagePath("Dalmatian.webp")
                            .build(),
                    Animal.builder()
                            .name("시프도그")
                            .grade(Grade.RARE)
                            .attackPower(45)
                            .defencePower(45)
                            .life(160)
                            .species(Species.DOG)
                            .imagePath("Sheepdog.webp")
                            .build(),
                    Animal.builder()
                            .name("차우차우")
                            .grade(Grade.RARE)
                            .attackPower(48)
                            .defencePower(48)
                            .life(175)
                            .species(Species.DOG)
                            .imagePath("ChowChow.webp")
                            .build(),
                    Animal.builder()
                            .name("세인트버나드")
                            .grade(Grade.RARE)
                            .attackPower(50)
                            .defencePower(50)
                            .life(180)
                            .species(Species.DOG)
                            .imagePath("StBernard.webp")
                            .build(),
                    Animal.builder()
                            .name("진돗개")
                            .grade(Grade.SUPERRARE)
                            .attackPower(88)
                            .defencePower(99)
                            .life(250)
                            .species(Species.DOG)
                            .imagePath("Jindo.webp")
                            .build(),
                    Animal.builder()
                            .name("사막여우")
                            .grade(Grade.SUPERRARE)
                            .attackPower(75)
                            .defencePower(90)
                            .life(240)
                            .species(Species.DOG)
                            .imagePath("DesertFox.webp")
                            .build(),
                    Animal.builder()
                            .name("시고르자브")
                            .grade(Grade.SUPERRARE)
                            .attackPower(70)
                            .defencePower(70)
                            .life(270)
                            .species(Species.DOG)
                            .imagePath("KoreanMongrel.webp")
                            .build(),
                    Animal.builder()
                            .name("코인도그")
                            .grade(Grade.SUPERRARE)
                            .attackPower(100)
                            .defencePower(10)
                            .life(260)
                            .species(Species.DOG)
                            .imagePath("Doge.webp")
                            .build(),
                    Animal.builder()
                            .name("핫도그")
                            .grade(Grade.SUPERRARE)
                            .attackPower(70)
                            .defencePower(70)
                            .life(265)
                            .species(Species.DOG)
                            .imagePath("Hotdog.webp")
                            .build(),
                    Animal.builder()
                            .name("물개")
                            .grade(Grade.SUPERRARE)
                            .attackPower(76)
                            .defencePower(82)
                            .life(255)
                            .species(Species.DOG)
                            .imagePath("Seal.webp")
                            .build(),
                    Animal.builder()
                            .name("북극여우")
                            .grade(Grade.SUPERRARE)
                            .attackPower(90)
                            .defencePower(70)
                            .life(270)
                            .species(Species.DOG)
                            .imagePath("PolarFox.webp")
                            .build(),
                    Animal.builder()
                            .name("사이보그개")
                            .grade(Grade.SUPERRARE)
                            .attackPower(97)
                            .defencePower(88)
                            .life(275)
                            .species(Species.DOG)
                            .imagePath("CybogDog.webp")
                            .build(),
                    Animal.builder()
                            .name("늑대왕")
                            .grade(Grade.UNIQUE)
                            .attackPower(169)
                            .defencePower(146)
                            .life(370)
                            .species(Species.DOG)
                            .imagePath("WolfKing.webp")
                            .build(),
                    Animal.builder()
                            .name("사이보그물개")
                            .grade(Grade.UNIQUE)
                            .attackPower(130)
                            .defencePower(180)
                            .life(380)
                            .species(Species.DOG)
                            .imagePath("CybogSeal.webp")
                            .build(),
                    Animal.builder()
                            .name("사이보그늑대")
                            .grade(Grade.UNIQUE)
                            .attackPower(180)
                            .defencePower(150)
                            .life(377)
                            .species(Species.DOG)
                            .imagePath("CybogWolf.webp")
                            .build(),
                    Animal.builder()
                            .name("구미호")
                            .grade(Grade.LEGEND)
                            .attackPower(197)
                            .defencePower(175)
                            .life(460)
                            .species(Species.DOG)
                            .imagePath("NineTailFox.webp")
                            .build(),
                    Animal.builder()
                            .name("늑대인간")
                            .grade(Grade.LEGEND)
                            .attackPower(185)
                            .defencePower(195)
                            .life(480)
                            .species(Species.DOG)
                            .imagePath("Werewolf.webp")
                            .build(),
                    Animal.builder()
                            .name("케로베로스")
                            .grade(Grade.LEGEND)
                            .attackPower(192)
                            .defencePower(189)
                            .life(500)
                            .species(Species.DOG)
                            .imagePath("Cerberus.webp")
                            .build(),


                    Animal.builder().name("먀아").grade(Grade.NORMAL).attackPower(11).defencePower(25).life(5).species(Species.CAT).imagePath("Mahah.webp").build(),
                    Animal.builder().name("물고양이").grade(Grade.NORMAL).attackPower(23).defencePower(22).life(22).species(Species.CAT).imagePath("WaterCat.webp").build(),
                    Animal.builder().name("마눌들고양이").grade(Grade.NORMAL).attackPower(5).defencePower(3).life(76).species(Species.CAT).imagePath("Manul.webp").build(),
                    Animal.builder().name("노트뤠이숲고양이").grade(Grade.NORMAL).attackPower(14).defencePower(13).life(65).species(Species.CAT).imagePath("NorwegianForestCat.webp").build(),
                    Animal.builder().name("렉돌").grade(Grade.NORMAL).attackPower(22).defencePower(8).life(9).species(Species.CAT).imagePath("Ragdoll.webp").build(),
                    Animal.builder().name("러시안블루").grade(Grade.NORMAL).attackPower(23).defencePower(14).life(4).species(Species.CAT).imagePath("RussianBlue.webp").build(),
                    Animal.builder().name("먼치킨").grade(Grade.NORMAL).attackPower(25).defencePower(30).life(40).species(Species.CAT).imagePath("Munchkin.webp").build(),
                    Animal.builder().name("뱅갈").grade(Grade.NORMAL).attackPower(15).defencePower(25).life(56).species(Species.CAT).imagePath("Bengal.webp").build(),
                    Animal.builder().name("브리티시쇼트헤어").grade(Grade.NORMAL).attackPower(10).defencePower(20).life(18).species(Species.CAT).imagePath("BritishShorthair.webp").build(),
                    Animal.builder().name("샴").grade(Grade.NORMAL).attackPower(6).defencePower(7).life(50).species(Species.CAT).imagePath("SiameseCat.webp").build(),
                    Animal.builder().name("스코티시폴드").grade(Grade.NORMAL).attackPower(13).defencePower(9).life(15).species(Species.CAT).imagePath("ScottishFold.webp").build(),
                    Animal.builder().name("스핑크스").grade(Grade.NORMAL).attackPower(12).defencePower(17).life(63).species(Species.CAT).imagePath("Sphynx.webp").build(),
                    Animal.builder().name("아메리칸쇼트헤어").grade(Grade.NORMAL).attackPower(7).defencePower(22).life(4).species(Species.CAT).imagePath("AmericanShorthair.webp").build(),
                    Animal.builder().name("아비시니아").grade(Grade.NORMAL).attackPower(3).defencePower(29).life(57).species(Species.CAT).imagePath("Abyssinia.webp").build(),
                    Animal.builder().name("코리안쇼트헤어").grade(Grade.NORMAL).attackPower(21).defencePower(10).life(43).species(Species.CAT).imagePath("KoreanShorthair.webp").build(),
                    Animal.builder().name("터키시앙고라").grade(Grade.NORMAL).attackPower(22).defencePower(0).life(69).species(Species.CAT).imagePath("TurkishAngora.webp").build(),
                    Animal.builder().name("페르시안").grade(Grade.NORMAL).attackPower(9).defencePower(27).life(43).species(Species.CAT).imagePath("Persian.webp").build(),
                    Animal.builder().name("길냥이").grade(Grade.NORMAL).attackPower(1).defencePower(15).life(36).species(Species.CAT).imagePath("Tortoiseshell.webp").build(),
                    Animal.builder().name("삼색이").grade(Grade.NORMAL).attackPower(23).defencePower(13).life(67).species(Species.CAT).imagePath("Calico.webp").build(),
                    Animal.builder().name("데본렉스").grade(Grade.NORMAL).attackPower(28).defencePower(3).life(62).species(Species.CAT).imagePath("DevonRex.webp").build(),
                    Animal.builder().name("싱가푸라").grade(Grade.NORMAL).attackPower(16).defencePower(9).life(0).species(Species.CAT).imagePath("Singapura.webp").build(),
                    Animal.builder().name("셀커크렉스").grade(Grade.NORMAL).attackPower(29).defencePower(11).life(48).species(Species.CAT).imagePath("SelkirkRex.webp").build(),
                    Animal.builder().name("라가머핀").grade(Grade.NORMAL).attackPower(27).defencePower(23).life(3).species(Species.CAT).imagePath("Ragamuffin.webp").build(),
                    Animal.builder().name("카라칼").grade(Grade.RARE).attackPower(50).defencePower(45).life(150).species(Species.CAT).imagePath("Caracal.webp").build(),
                    Animal.builder().name("고먐미").grade(Grade.RARE).attackPower(30).defencePower(30).life(120).species(Species.CAT).imagePath("SqureCat.webp").build(),
                    Animal.builder().name("서벌").grade(Grade.RARE).attackPower(55).defencePower(30).life(180).species(Species.CAT).imagePath("Serval.webp").build(),
                    Animal.builder().name("하이에나").grade(Grade.RARE).attackPower(48).defencePower(43).life(160).species(Species.CAT).imagePath("Hyena.webp").build(),
                    Animal.builder().name("왕발고양이").grade(Grade.RARE).attackPower(56).defencePower(52).life(190).species(Species.CAT).imagePath("BigFootCat.webp").build(),
                    Animal.builder().name("사자").grade(Grade.RARE).attackPower(59).defencePower(55).life(200).species(Species.CAT).imagePath("Lion.webp").build(),
                    Animal.builder().name("루왁커피냥").grade(Grade.RARE).attackPower(31).defencePower(47).life(170).species(Species.CAT).imagePath("CoffeeCat.webp").build(),
                    Animal.builder().name("제규어").grade(Grade.RARE).attackPower(58).defencePower(54).life(195).species(Species.CAT).imagePath("Jaguar.webp").build(),
                    Animal.builder().name("표범").grade(Grade.RARE).attackPower(53).defencePower(49).life(185).species(Species.CAT).imagePath("Leopard.webp").build(),
                    Animal.builder().name("치타").grade(Grade.RARE).attackPower(60).defencePower(60).life(200).species(Species.CAT).imagePath("Cheetah.webp").build(),
                    Animal.builder().name("퓨마").grade(Grade.RARE).attackPower(57).defencePower(53).life(192).species(Species.CAT).imagePath("Puma.webp").build(),
                    Animal.builder().name("삵").grade(Grade.RARE).attackPower(46).defencePower(42).life(140).species(Species.CAT).imagePath("LeopardCat.webp").build(),
                    Animal.builder().name("오셀롯").grade(Grade.RARE).attackPower(54).defencePower(48).life(165).species(Species.CAT).imagePath("Ocelot.webp").build(),
                    Animal.builder().name("스라소니").grade(Grade.RARE).attackPower(40).defencePower(44).life(155).species(Species.CAT).imagePath("EurasianIynx.webp").build(),
                    Animal.builder().name("백호").grade(Grade.SUPERRARE).attackPower(75).defencePower(65).life(250).species(Species.CAT).imagePath("WhiteTiger.webp").build(),
                    Animal.builder().name("담배피던시절 호랑이").grade(Grade.SUPERRARE).attackPower(85).defencePower(75).life(275).species(Species.CAT).imagePath("SmokingTiger.webp").build(),
                    Animal.builder().name("냥냥펀치고양이").grade(Grade.SUPERRARE).attackPower(80).defencePower(70).life(260).species(Species.CAT).imagePath("PunchCat.webp").build(),
                    Animal.builder().name("해피캣").grade(Grade.SUPERRARE).attackPower(65).defencePower(80).life(290).species(Species.CAT).imagePath("HappyCat.webp").build(),
                    Animal.builder().name("라이거").grade(Grade.SUPERRARE).attackPower(95).defencePower(85).life(300).species(Species.CAT).imagePath("Liger.webp").build(),
                    Animal.builder().name("한복고양이").grade(Grade.SUPERRARE).attackPower(70).defencePower(60).life(230).species(Species.CAT).imagePath("HanbokCat.webp").build(),
                    Animal.builder().name("강철고양이").grade(Grade.SUPERRARE).attackPower(100).defencePower(100).life(300).species(Species.CAT).imagePath("MilitaCat.webp").build(),
                    Animal.builder().name("구름표범").grade(Grade.SUPERRARE).attackPower(88).defencePower(78).life(280).species(Species.CAT).imagePath("CloudLeopard.webp").build(),
                    Animal.builder().name("스밀로돈").grade(Grade.UNIQUE).attackPower(120).defencePower(110).life(380).species(Species.CAT).imagePath("Smilodon.webp").build(),
                    Animal.builder().name("네로").grade(Grade.UNIQUE).attackPower(135).defencePower(125).life(390).species(Species.CAT).imagePath("Nero.webp").build(),
                    Animal.builder().name("오드아이캣").grade(Grade.UNIQUE).attackPower(130).defencePower(120).life(370).species(Species.CAT).imagePath("OddEyesCat.webp").build(),
                    Animal.builder().name("바스테트").grade(Grade.LEGEND).attackPower(180).defencePower(170).life(480).species(Species.CAT).imagePath("Bastet.webp").build(),
                    Animal.builder().name("해태").grade(Grade.LEGEND).attackPower(195).defencePower(190).life(490).species(Species.CAT).imagePath("Haetae.webp").build(),
                    Animal.builder().name("네코마타").grade(Grade.LEGEND).attackPower(200).defencePower(200).life(500).species(Species.CAT).imagePath("Nekomata.webp").build(),

                    Animal.builder().name("닭").grade(Grade.NORMAL).attackPower(23).defencePower(15).life(60).species(Species.BIRD).imagePath("Chicken.webp").build(),
                    Animal.builder().name("오리").grade(Grade.NORMAL).attackPower(21).defencePower(16).life(72).species(Species.BIRD).imagePath("Duck.webp").build(),
                    Animal.builder().name("비둘기").grade(Grade.NORMAL).attackPower(14).defencePower(17).life(50).species(Species.BIRD).imagePath("Pigeon.webp").build(),
                    Animal.builder().name("꿩").grade(Grade.NORMAL).attackPower(20).defencePower(21).life(91).species(Species.BIRD)
                            .imagePath("Pheasant.webp").build(),
                    Animal.builder().name("매").grade(Grade.NORMAL).attackPower(24).defencePower(21).life(68).species(Species.BIRD).imagePath("Hawk.webp").build(),
                    Animal.builder().name("거위").grade(Grade.NORMAL).attackPower(15).defencePower(24).life(42).species(Species.BIRD).imagePath("Goose.webp").build(),
                    Animal.builder().name("황새").grade(Grade.NORMAL).attackPower(25).defencePower(20).life(75).species(Species.BIRD).imagePath("Stork.webp").build(),
                    Animal.builder().name("두루미").grade(Grade.NORMAL).attackPower(18).defencePower(22).life(55).species(Species.BIRD).imagePath("Crane.webp").build(),
                    Animal.builder().name("백조").grade(Grade.NORMAL).attackPower(27).defencePower(18).life(80).species(Species.BIRD).imagePath("Swan.webp").build(),
                    Animal.builder().name("뻐꾸기").grade(Grade.NORMAL).attackPower(19).defencePower(23).life(47).species(Species.BIRD).imagePath("Cuckoo.webp").build(),
                    Animal.builder().name("찌르레기").grade(Grade.NORMAL).attackPower(22).defencePower(19).life(63).species(Species.BIRD).imagePath("Starling.webp").build(),
                    Animal.builder().name("할미새").grade(Grade.NORMAL).attackPower(17).defencePower(20).life(51).species(Species.BIRD).imagePath("Wagtail.webp").build(),
                    Animal.builder().name("도요새").grade(Grade.NORMAL).attackPower(20).defencePower(18).life(49).species(Species.BIRD).imagePath("Snipe.webp").build(),
                    Animal.builder().name("갈매기").grade(Grade.NORMAL).attackPower(16).defencePower(25).life(38).species(Species.BIRD).imagePath("Gull.webp").build(),
                    Animal.builder().name("가마우지").grade(Grade.NORMAL).attackPower(19).defencePower(22).life(44).species(Species.BIRD).imagePath("Cormorant.webp").build(),
                    Animal.builder().name("펭귄").grade(Grade.NORMAL).attackPower(25).defencePower(20).life(60).species(Species.BIRD).imagePath("Penquin.webp").build(),
                    Animal.builder().name("뜸부기").grade(Grade.NORMAL).attackPower(20).defencePower(19).life(58).species(Species.BIRD).imagePath("Crake.webp").build(),
                    Animal.builder().name("어치").grade(Grade.NORMAL).attackPower(22).defencePower(17).life(52).species(Species.BIRD).imagePath("Jay.webp").build(),
                    Animal.builder().name("까치").grade(Grade.NORMAL).attackPower(18).defencePower(23).life(55).species(Species.BIRD).imagePath("Magpie.webp").build(),
                    Animal.builder().name("원앙").grade(Grade.NORMAL).attackPower(24).defencePower(18).life(68).species(Species.BIRD).imagePath("Mandarin_duck.webp").build(),
                    Animal.builder().name("잉꼬").grade(Grade.NORMAL).attackPower(21).defencePower(16).life(70).species(Species.BIRD).imagePath("Parakeet.webp").build(),
                    Animal.builder().name("부엉이").grade(Grade.NORMAL).attackPower(23).defencePower(15).life(65).species(Species.BIRD).imagePath("Owl.webp").build(),
                    Animal.builder().name("앵무새").grade(Grade.RARE).attackPower(50).defencePower(50).life(150).species(Species.BIRD).imagePath("Parrot.webp").build(),
                    Animal.builder().name("기러기").grade(Grade.RARE).attackPower(54).defencePower(45).life(160).species(Species.BIRD).imagePath("Wild_goose.webp").build(),
                    Animal.builder().name("타조").grade(Grade.RARE).attackPower(40).defencePower(40).life(180).species(Species.BIRD).imagePath("Ostrich.webp").build(),
                    Animal.builder().name("카나리아").grade(Grade.RARE).attackPower(55).defencePower(30).life(150).species(Species.BIRD).imagePath("Canary.webp").build(),
                    Animal.builder().name("공작새").grade(Grade.RARE).attackPower(40).defencePower(55).life(170).species(Species.BIRD).imagePath("Peacock.webp").build(),
                    Animal.builder().name("칠면조").grade(Grade.RARE).attackPower(60).defencePower(30).life(120).species(Species.BIRD).imagePath("Turkey.webp").build(),
                    Animal.builder().name("펠리컨").grade(Grade.RARE).attackPower(55).defencePower(35).life(150).species(Species.BIRD).imagePath("Pelican.webp").build(),
                    Animal.builder().name("제비").grade(Grade.RARE).attackPower(55).defencePower(55).life(110).species(Species.BIRD).imagePath("Swallow.webp").build(),
                    Animal.builder().name("참새").grade(Grade.RARE).attackPower(42).defencePower(51).life(160).species(Species.BIRD).imagePath("Sparrow.webp").build(),
                    Animal.builder().name("흰비둘기").grade(Grade.RARE).attackPower(46).defencePower(55).life(170).species(Species.BIRD).imagePath("WhitePigeon.webp").build(),
                    Animal.builder().name("딱새").grade(Grade.RARE).attackPower(52).defencePower(45).life(180).species(Species.BIRD).imagePath("DaurianRedstart.webp").build(),
                    Animal.builder().name("황제펭귄").grade(Grade.RARE).attackPower(38).defencePower(40).life(200).species(Species.BIRD).imagePath("EmperorPenguin.webp").build(),
                    Animal.builder().name("설까치").grade(Grade.RARE).attackPower(54).defencePower(40).life(170).species(Species.BIRD).imagePath("OrientalMagpie.webp").build(),
                    Animal.builder().name("벌새").grade(Grade.RARE).attackPower(50).defencePower(42).life(165).species(Species.BIRD).imagePath("BeeBird.webp").build(),
                    Animal.builder().name("파랑새").grade(Grade.SUPERRARE).attackPower(75).defencePower(80).life(250).species(Species.BIRD).imagePath("DollarBird.webp").build(),
                    Animal.builder().name("물총새").grade(Grade.SUPERRARE).attackPower(90).defencePower(75).life(260).species(Species.BIRD).imagePath("WatergunBird.webp").build(),
                    Animal.builder().name("왕타조알").grade(Grade.SUPERRARE).attackPower(85).defencePower(85).life(250).species(Species.BIRD).imagePath("BigOstrichEgg.webp").build(),
                    Animal.builder().name("대머리독수리").grade(Grade.SUPERRARE).attackPower(95).defencePower(70).life(250).species(Species.BIRD).imagePath("BaldEagle.webp").build(),
                    Animal.builder().name("청동오리").grade(Grade.SUPERRARE).attackPower(100).defencePower(75).life(240).species(Species.BIRD).imagePath("BronzeDuck.webp").build(),
                    Animal.builder().name("키위새").grade(Grade.SUPERRARE).attackPower(80).defencePower(80).life(270).species(Species.BIRD).imagePath("KiwiBird.webp").build(),
                    Animal.builder().name("이잉칙힌").grade(Grade.SUPERRARE).attackPower(65).defencePower(95).life(280).species(Species.BIRD).imagePath("IngChicken.webp").build(),
                    Animal.builder().name("쌍두타조").grade(Grade.SUPERRARE).attackPower(80).defencePower(95).life(250).species(Species.BIRD).imagePath("TwoHeadOstrich.webp").build(),
                    Animal.builder().name("전기병아리").grade(Grade.UNIQUE).attackPower(140).defencePower(100).life(350).species(Species.BIRD).imagePath("EletricChick.webp").build(),
                    Animal.builder().name("마하버드").grade(Grade.UNIQUE).attackPower(130).defencePower(110).life(370).species(Species.BIRD).imagePath("MatchBird.webp").build(),
                    Animal.builder().name("시조새").grade(Grade.UNIQUE).attackPower(120).defencePower(140).life(400).species(Species.BIRD).imagePath("Archeopteryx.webp").build(),
                    Animal.builder().name("피닉스").grade(Grade.LEGEND).attackPower(200).defencePower(150).life(450).species(Species.BIRD).imagePath("Phoenix.webp").build(),
                    Animal.builder().name("가루다").grade(Grade.LEGEND).attackPower(170).defencePower(170).life(470).species(Species.BIRD).imagePath("Garuda.webp").build(),
                    Animal.builder().name("그리핀").grade(Grade.LEGEND).attackPower(150).defencePower(200).life(500).species(Species.BIRD).imagePath("Gryffin.webp").build(),

                    Animal.builder().name("해파리").grade(Grade.NORMAL).attackPower(30).defencePower(10).life(1).species(Species.FISH).imagePath("JellyFish.webp").build(),
                    Animal.builder().name("고등어").grade(Grade.NORMAL).attackPower(10).defencePower(10).life(100).species(Species.FISH).imagePath("Mackerel.webp").build(),
                    Animal.builder().name("삼치").grade(Grade.NORMAL).attackPower(20).defencePower(20).life(98).species(Species.FISH).imagePath("JapanMackerel.webp").build(),
                    Animal.builder().name("연어").grade(Grade.NORMAL).attackPower(14).defencePower(14).life(88).species(Species.FISH).imagePath("Salmon.webp").build(),
                    Animal.builder().name("송사리").grade(Grade.NORMAL).attackPower(7).defencePower(7).life(7).species(Species.FISH).imagePath("Minnow.webp").build(),
                    Animal.builder().name("금붕어").grade(Grade.NORMAL).attackPower(7).defencePower(7).life(7).species(Species.FISH).imagePath("Goldfish.webp").build(),
                    Animal.builder().name("불가사리").grade(Grade.NORMAL).attackPower(19).defencePower(19).life(86).species(Species.FISH).imagePath("Starfish.webp").build(),
                    Animal.builder().name("망둥어").grade(Grade.NORMAL).attackPower(21).defencePower(21).life(29).species(Species.FISH).imagePath("Hoppfish.webp").build(),
                    Animal.builder().name("전어").grade(Grade.NORMAL).attackPower(19).defencePower(21).life(77).species(Species.FISH).imagePath("Shad.webp").build(),
                    Animal.builder().name("새우").grade(Grade.NORMAL).attackPower(21).defencePower(19).life(78).species(Species.FISH).imagePath("Shirmp.webp").build(),
                    Animal.builder().name("선어").grade(Grade.NORMAL).attackPower(30).defencePower(30).life(69).species(Species.FISH).imagePath("FreshFish.webp").build(),
                    Animal.builder().name("바지락").grade(Grade.NORMAL).attackPower(5).defencePower(30).life(91).species(Species.FISH).imagePath("ManilaClam.webp").build(),
                    Animal.builder().name("플랑크톤").grade(Grade.NORMAL).attackPower(30).defencePower(30).life(100).species(Species.FISH).imagePath("Plankton.webp").build(),
                    Animal.builder().name("쥐치").grade(Grade.NORMAL).attackPower(25).defencePower(16).life(78).species(Species.FISH).imagePath("Filefish.webp").build(),
                    Animal.builder().name("구피").grade(Grade.NORMAL).attackPower(27).defencePower(30).life(77).species(Species.FISH).imagePath("Guppy.webp").build(),
                    Animal.builder().name("메기").grade(Grade.NORMAL).attackPower(19).defencePower(21).life(21).species(Species.FISH).imagePath("Catfish.webp").build(),
                    Animal.builder().name("볼락").grade(Grade.NORMAL).attackPower(18).defencePower(18).life(81).species(Species.FISH).imagePath("Bolak.webp").build(),
                    Animal.builder().name("우럭").grade(Grade.NORMAL).attackPower(15).defencePower(15).life(75).species(Species.FISH).imagePath("URuk.webp").build(),
                    Animal.builder().name("가자미").grade(Grade.NORMAL).attackPower(19).defencePower(19).life(70).species(Species.FISH).imagePath("TongueSoleFish.webp").build(),
                    Animal.builder().name("방어").grade(Grade.NORMAL).attackPower(25).defencePower(14).life(77).species(Species.FISH).imagePath("Amberjack.webp").build(),
                    Animal.builder().name("광어").grade(Grade.NORMAL).attackPower(13).defencePower(27).life(78).species(Species.FISH).imagePath("Flatfish.webp").build(),
                    Animal.builder().name("숭어").grade(Grade.NORMAL).attackPower(14).defencePower(19).life(90).species(Species.FISH).imagePath("Mullet.webp").build(),
                    Animal.builder().name("개복치").grade(Grade.RARE).attackPower(31).defencePower(60).life(195).species(Species.FISH).imagePath("OceanSunfish.webp").build(),
                    Animal.builder().name("피라냐").grade(Grade.RARE).attackPower(55).defencePower(31).life(142).species(Species.FISH).imagePath("Piranha.webp").build(),
                    Animal.builder().name("해마").grade(Grade.RARE).attackPower(31).defencePower(31).life(200).species(Species.FISH).imagePath("SeaHorse.webp").build(),
                    Animal.builder().name("아귀").grade(Grade.RARE).attackPower(60).defencePower(44).life(145).species(Species.FISH).imagePath("Anglerfish.webp").build(),
                    Animal.builder().name("곰치").grade(Grade.RARE).attackPower(49).defencePower(49).life(165).species(Species.FISH).imagePath("MorayEel.webp").build(),
                    Animal.builder().name("대왕조개").grade(Grade.RARE).attackPower(35).defencePower(60).life(200).species(Species.FISH).imagePath("GiantClam.webp").build(),
                    Animal.builder().name("다금바리").grade(Grade.RARE).attackPower(38).defencePower(56).life(177).species(Species.FISH).imagePath("Grouper.webp").build(),
                    Animal.builder().name("전기뱀장어").grade(Grade.RARE).attackPower(60).defencePower(45).life(178).species(Species.FISH).imagePath("ElectricEel.webp").build(),
                    Animal.builder().name("복어").grade(Grade.RARE).attackPower(47).defencePower(55).life(123).species(Species.FISH).imagePath("BlowFish.webp").build(),
                    Animal.builder().name("랍스터").grade(Grade.RARE).attackPower(55).defencePower(55).life(132).species(Species.FISH).imagePath("Lobster.webp").build(),
                    Animal.builder().name("꽃게").grade(Grade.RARE).attackPower(54).defencePower(58).life(114).species(Species.FISH).imagePath("Crab.webp").build(),
                    Animal.builder().name("독해파리").grade(Grade.RARE).attackPower(60).defencePower(31).life(155).species(Species.FISH).imagePath("PoisonJellyfish.webp").build(),
                    Animal.builder().name("박대").grade(Grade.RARE).attackPower(55).defencePower(39).life(166).species(Species.FISH).imagePath("TongueSoleFish.webp").build(),
                    Animal.builder().name("갈치").grade(Grade.RARE).attackPower(47).defencePower(39).life(101).species(Species.FISH).imagePath("HairTailFish.webp").build(),
                    Animal.builder().name("대왕고래").grade(Grade.SUPERRARE).attackPower(100).defencePower(100).life(300).species(Species.FISH).imagePath("GiantWhale.webp").build(),
                    Animal.builder().name("범고래").grade(Grade.SUPERRARE).attackPower(95).defencePower(95).life(270).species(Species.FISH).imagePath("KillerWhale.webp").build(),
                    Animal.builder().name("물귀신").grade(Grade.SUPERRARE).attackPower(90).defencePower(90).life(250).species(Species.FISH).imagePath("WaterGhost.webp").build(),
                    Animal.builder().name("식인상어").grade(Grade.SUPERRARE).attackPower(95).defencePower(85).life(260).species(Species.FISH).imagePath("Shark.webp").build(),
                    Animal.builder().name("돛새치").grade(Grade.SUPERRARE).attackPower(95).defencePower(80).life(260).species(Species.FISH).imagePath("Sailfish.webp").build(),
                    Animal.builder().name("인면어").grade(Grade.SUPERRARE).attackPower(90).defencePower(90).life(300).species(Species.FISH).imagePath("HumanFaceFish.webp").build(),
                    Animal.builder().name("피라루쿠").grade(Grade.SUPERRARE).attackPower(85).defencePower(100).life(275).species(Species.FISH).imagePath("Pirarucu.webp").build(),
                    Animal.builder().name("황금잉어").grade(Grade.SUPERRARE).attackPower(70).defencePower(75).life(300).species(Species.FISH).imagePath("GoldenCarp.webp").build(),
                    Animal.builder().name("악마고래").grade(Grade.UNIQUE).attackPower(130).defencePower(130).life(380).species(Species.FISH).imagePath("DevilWhale.webp").build(),
                    Animal.builder().name("세이렌").grade(Grade.UNIQUE).attackPower(140).defencePower(120).life(320).species(Species.FISH).imagePath("Siren.webp").build(),
                    Animal.builder().name("거북섬").grade(Grade.UNIQUE).attackPower(110).defencePower(140).life(400).species(Species.FISH).imagePath("TurtleIsland.webp").build(),
                    Animal.builder().name("크라켄").grade(Grade.LEGEND).attackPower(182).defencePower(180).life(465).species(Species.FISH).imagePath("Kraken.webp").build(),
                    Animal.builder().name("레비아탄").grade(Grade.LEGEND).attackPower(198).defencePower(150).life(425).species(Species.FISH).imagePath("Leviathan.webp").build(),
                    Animal.builder().name("카립디스").grade(Grade.LEGEND).attackPower(152).defencePower(197).life(500).species(Species.FISH).imagePath("Charybdis.webp").build(),


                    Animal.builder().name("맷밭쥐").grade(Grade.NORMAL).attackPower(17).defencePower(19).life(55).species(Species.GLIRES).imagePath("HarvestRat.webp").build(),
                    Animal.builder().name("다람쥐").grade(Grade.NORMAL).attackPower(30).defencePower(30).life(100).species(Species.GLIRES).imagePath("Chipmunk.webp").build(),
                    Animal.builder().name("시궁창쥐").grade(Grade.NORMAL).attackPower(10).defencePower(10).life(40).species(Species.GLIRES).imagePath("GutterRat.webp").build(),
                    Animal.builder().name("래트").grade(Grade.NORMAL).attackPower(16).defencePower(18).life(55).species(Species.GLIRES).imagePath("Rat.webp").build(),
                    Animal.builder().name("토끼").grade(Grade.NORMAL).attackPower(15).defencePower(22).life(85).species(Species.GLIRES).imagePath("Rabbit.webp").build(),
                    Animal.builder().name("기니피그").grade(Grade.NORMAL).attackPower(13).defencePower(20).life(60).species(Species.GLIRES).imagePath("GuineaPig.webp").build(),
                    Animal.builder().name("마멋").grade(Grade.NORMAL).attackPower(14).defencePower(21).life(58).species(Species.GLIRES).imagePath("GroundHog.webp").build(),
                    Animal.builder().name("저빌").grade(Grade.NORMAL).attackPower(15).defencePower(20).life(56).species(Species.GLIRES).imagePath("Gerbil.webp").build(),
                    Animal.builder().name("박쥐").grade(Grade.NORMAL).attackPower(20).defencePower(18).life(50).species(Species.GLIRES).imagePath("Bat.webp").build(),
                    Animal.builder().name("흰쥐").grade(Grade.NORMAL).attackPower(15).defencePower(15).life(60).species(Species.GLIRES).imagePath("WhiteMouse.webp").build(),
                    Animal.builder().name("친칠라").grade(Grade.NORMAL).attackPower(18).defencePower(23).life(70).species(Species.GLIRES).imagePath("Chinchilla.webp").build(),
                    Animal.builder().name("프레리도그").grade(Grade.NORMAL).attackPower(22).defencePower(24).life(78).species(Species.GLIRES).imagePath("Prairiedog.webp").build(),
                    Animal.builder().name("청설모").grade(Grade.NORMAL).attackPower(15).defencePower(22).life(60).species(Species.GLIRES).imagePath("Squirrel.webp").build(),
                    Animal.builder().name("카피바라").grade(Grade.NORMAL).attackPower(14).defencePower(19).life(65).species(Species.GLIRES).imagePath("Capybara.webp").build(),
                    Animal.builder().name("파카").grade(Grade.NORMAL).attackPower(17).defencePower(20).life(62).species(Species.GLIRES).imagePath("Paka.webp").build(),
                    Animal.builder().name("레밍").grade(Grade.NORMAL).attackPower(12).defencePower(14).life(45).species(Species.GLIRES).imagePath("Lemming.webp").build(),
                    Animal.builder().name("골든햄스터").grade(Grade.NORMAL).attackPower(14).defencePower(20).life(58).species(Species.GLIRES).imagePath("GoldenHamster.webp").build(),
                    Animal.builder().name("드워프햄스터").grade(Grade.NORMAL).attackPower(13).defencePower(19).life(57).species(Species.GLIRES).imagePath("DwarfHamster.webp").build(),
                    Animal.builder().name("슈가글라이더").grade(Grade.NORMAL).attackPower(21).defencePower(22).life(80).species(Species.GLIRES).imagePath("SugarGlider.webp").build(),
                    Animal.builder().name("뉴트리아").grade(Grade.NORMAL).attackPower(18).defencePower(25).life(82).species(Species.GLIRES).imagePath("Nutria.webp").build(),
                    Animal.builder().name("비버").grade(Grade.NORMAL).attackPower(20).defencePower(28).life(90).species(Species.GLIRES).imagePath("Beaver.webp").build(),
                    Animal.builder().name("호저").grade(Grade.NORMAL).attackPower(15).defencePower(20).life(75).species(Species.GLIRES).imagePath("Porcupine.webp").build(),
                    Animal.builder().name("서울쥐").grade(Grade.RARE).attackPower(45).defencePower(35).life(150).species(Species.GLIRES).imagePath("SeoulMouse.webp").build(),
                    Animal.builder().name("젤리쥐").grade(Grade.RARE).attackPower(52).defencePower(38).life(145).species(Species.GLIRES).imagePath("JellyMouse.webp").build(),
                    Animal.builder().name("벌거숭이두더지쥐").grade(Grade.RARE).attackPower(40).defencePower(45).life(160).species(Species.GLIRES).imagePath("NakedMoleRat.webp").build(),
                    Animal.builder().name("병사쥐").grade(Grade.RARE).attackPower(48).defencePower(40).life(170).species(Species.GLIRES).imagePath("SoldierMouse.webp").build(),
                    Animal.builder().name("멋쟁이쥐").grade(Grade.RARE).attackPower(55).defencePower(32).life(155).species(Species.GLIRES).imagePath("FashionMouse.webp").build(),
                    Animal.builder().name("해골쥐").grade(Grade.RARE).attackPower(42).defencePower(42).life(180).species(Species.GLIRES).imagePath("SkeletonMouse.webp").build(),
                    Animal.builder().name("해적쥐").grade(Grade.RARE).attackPower(50).defencePower(36).life(165).species(Species.GLIRES).imagePath("PirateMouse.webp").build(),
                    Animal.builder().name("경찰쥐").grade(Grade.RARE).attackPower(47).defencePower(39).life(175).species(Species.GLIRES).imagePath("PoliceMouse.webp").build(),
                    Animal.builder().name("골렘쥐").grade(Grade.RARE).attackPower(44).defencePower(41).life(190).species(Species.GLIRES).imagePath("GolemMouse.webp").build(),
                    Animal.builder().name("나무쥐").grade(Grade.RARE).attackPower(52).defencePower(33).life(150).species(Species.GLIRES).imagePath("WoodenMouse.webp").build(),
                    Animal.builder().name("천사쥐").grade(Grade.RARE).attackPower(49).defencePower(38).life(185).species(Species.GLIRES).imagePath("AngelMouse.webp").build(),
                    Animal.builder().name("악마쥐").grade(Grade.RARE).attackPower(54).defencePower(37).life(165).species(Species.GLIRES).imagePath("DevilMouse.webp").build(),
                    Animal.builder().name("박사쥐").grade(Grade.RARE).attackPower(43).defencePower(44).life(178).species(Species.GLIRES).imagePath("ScientistMouse.webp").build(),
                    Animal.builder().name("유령쥐").grade(Grade.RARE).attackPower(46).defencePower(39).life(160).species(Species.GLIRES).imagePath("ReaperMouse.webp").build(),
                    Animal.builder().name("3대500헬창쥐").grade(Grade.SUPERRARE).attackPower(85).defencePower(70).life(300).species(Species.GLIRES).imagePath("HealthMouse.webp").build(),
                    Animal.builder().name("역병쥐").grade(Grade.SUPERRARE).attackPower(90).defencePower(65).life(230).species(Species.GLIRES).imagePath("PlagueMouse.webp").build(),
                    Animal.builder().name("쥐돌이").grade(Grade.SUPERRARE).attackPower(88).defencePower(62).life(275).species(Species.GLIRES).imagePath("MouseDori.webp").build(),
                    Animal.builder().name("비버킹").grade(Grade.SUPERRARE).attackPower(80).defencePower(75).life(260).species(Species.GLIRES).imagePath("BeaverKing.webp").build(),
                    Animal.builder().name("산미치광이호저").grade(Grade.SUPERRARE).attackPower(92).defencePower(68).life(290).species(Species.GLIRES).imagePath("CrazyPorcupine.webp").build(),
                    Animal.builder().name("초거대토끼").grade(Grade.SUPERRARE).attackPower(78).defencePower(77).life(240).species(Species.GLIRES).imagePath("GiantRabbit.webp").build(),
                    Animal.builder().name("쥐스페라도").grade(Grade.SUPERRARE).attackPower(97).defencePower(90).life(250).species(Species.GLIRES).imagePath("CowBoyMouse.webp").build(),
                    Animal.builder().name("황금박쥐").grade(Grade.SUPERRARE).attackPower(95).defencePower(60).life(265).species(Species.GLIRES).imagePath("GoldenBat.webp").build(),
                    Animal.builder().name("콩쥐").grade(Grade.UNIQUE).attackPower(120).defencePower(140).life(370).species(Species.GLIRES).imagePath("Kongjwi.webp").build(),
                    Animal.builder().name("팥쥐").grade(Grade.UNIQUE).attackPower(137).defencePower(115).life(330).species(Species.GLIRES).imagePath("PatJwi.webp").build(),
                    Animal.builder().name("쥐튜버").grade(Grade.UNIQUE).attackPower(128).defencePower(126).life(365).species(Species.GLIRES).imagePath("MouseTube.webp").build(),
                    Animal.builder().name("괴물쥐").grade(Grade.LEGEND).attackPower(200).defencePower(150).life(435).species(Species.GLIRES).imagePath("MonsterRat.webp").build(),
                    Animal.builder().name("쥐피티").grade(Grade.LEGEND).attackPower(177).defencePower(174).life(470).species(Species.GLIRES).imagePath("MousePT.webp").build(),
                    Animal.builder().name("쥐드래곤").grade(Grade.LEGEND).attackPower(175).defencePower(183).life(449).species(Species.GLIRES).imagePath("MouseDragon.webp").build(),



                    Animal.builder().name("코끼리").grade(Grade.NORMAL).attackPower(28).defencePower(28).life(90).species(Species.COMMON).imagePath("Elephant.webp").build(),
                    Animal.builder().name("기린").grade(Grade.NORMAL).attackPower(15).defencePower(18).life(70).species(Species.COMMON).imagePath("Giraffe.webp").build(),
                    Animal.builder().name("코뿔소").grade(Grade.NORMAL).attackPower(26).defencePower(25).life(85).species(Species.COMMON).imagePath("Rhino.webp").build(),
                    Animal.builder().name("지네").grade(Grade.NORMAL).attackPower(20).defencePower(15).life(50).species(Species.COMMON).imagePath("Centipede.webp").build(),
                    Animal.builder().name("거미").grade(Grade.NORMAL).attackPower(10).defencePower(10).life(40).species(Species.COMMON).imagePath("Spider.webp").build(),
                    Animal.builder().name("원숭이").grade(Grade.NORMAL).attackPower(18).defencePower(16).life(65).species(Species.COMMON).imagePath("Monkey.webp").build(),
                    Animal.builder().name("곰").grade(Grade.NORMAL).attackPower(27).defencePower(27).life(95).species(Species.COMMON).imagePath("Bear.webp").build(),
                    Animal.builder().name("사슴").grade(Grade.NORMAL).attackPower(13).defencePower(14).life(60).species(Species.COMMON).imagePath("Deer.webp").build(),
                    Animal.builder().name("돼지").grade(Grade.NORMAL).attackPower(14).defencePower(15).life(65).species(Species.COMMON).imagePath("Pig.webp").build(),
                    Animal.builder().name("소").grade(Grade.NORMAL).attackPower(20).defencePower(20).life(80).species(Species.COMMON).imagePath("Bull.webp").build(),
                    Animal.builder().name("뱀").grade(Grade.NORMAL).attackPower(15).defencePower(12).life(55).species(Species.COMMON).imagePath("Snake.webp").build(),
                    Animal.builder().name("악어").grade(Grade.NORMAL).attackPower(28).defencePower(28).life(88).species(Species.COMMON).imagePath("Crocodile.webp").build(),
                    Animal.builder().name("도마뱀").grade(Grade.NORMAL).attackPower(13).defencePower(10).life(50).species(Species.COMMON).imagePath("Lizard.webp").build(),
                    Animal.builder().name("개미핥기").grade(Grade.NORMAL).attackPower(5).defencePower(6).life(20).species(Species.COMMON).imagePath("AntEater.webp").build(),
                    Animal.builder().name("양").grade(Grade.NORMAL).attackPower(12).defencePower(15).life(58).species(Species.COMMON).imagePath("Sheep.webp").build(),
                    Animal.builder().name("염소").grade(Grade.NORMAL).attackPower(14).defencePower(16).life(60).species(Species.COMMON).imagePath("Goat.webp").build(),
                    Animal.builder().name("개구리").grade(Grade.NORMAL).attackPower(8).defencePower(8).life(40).species(Species.COMMON).imagePath("Frog.webp").build(),
                    Animal.builder().name("낙타").grade(Grade.NORMAL).attackPower(20).defencePower(20).life(85).species(Species.COMMON).imagePath("Camel.webp").build(),
                    Animal.builder().name("말").grade(Grade.NORMAL).attackPower(18).defencePower(18).life(75).species(Species.COMMON).imagePath("Horse.webp").build(),
                    Animal.builder().name("캥거루").grade(Grade.NORMAL).attackPower(20).defencePower(20).life(70).species(Species.COMMON).imagePath("Kangaroo.webp").build(),
                    Animal.builder().name("타란튤라").grade(Grade.RARE).attackPower(32).defencePower(30).life(110).species(Species.COMMON).imagePath("Tarantula.webp").build(),
                    Animal.builder().name("반달가슴곰").grade(Grade.RARE).attackPower(40).defencePower(55).life(150).species(Species.COMMON).imagePath("AsiaticBear.webp").build(),
                    Animal.builder().name("젖소").grade(Grade.RARE).attackPower(34).defencePower(52).life(120).species(Species.COMMON).imagePath("MilkCow.webp").build(),
                    Animal.builder().name("목도리도마뱀").grade(Grade.RARE).attackPower(36).defencePower(32).life(130).species(Species.COMMON).imagePath("ScarfLizard.webp").build(),
                    Animal.builder().name("산양").grade(Grade.RARE).attackPower(42).defencePower(40).life(135).species(Species.COMMON).imagePath("MountainGoat.webp").build(),
                    Animal.builder().name("황소개구리").grade(Grade.RARE).attackPower(31).defencePower(30).life(110).species(Species.COMMON).imagePath("BullFrog.webp").build(),
                    Animal.builder().name("뿔코끼리").grade(Grade.RARE).attackPower(55).defencePower(58).life(190).species(Species.COMMON).imagePath("HornedElephant.webp").build(),
                    Animal.builder().name("아르마딜로").grade(Grade.RARE).attackPower(38).defencePower(55).life(145).species(Species.COMMON).imagePath("Armadillo.webp").build(),
                    Animal.builder().name("대왕멧돼지").grade(Grade.SUPERRARE).attackPower(85).defencePower(90).life(230).species(Species.COMMON).imagePath("WildBoar.webp").build(),
                    Animal.builder().name("자이언트고릴라").grade(Grade.SUPERRARE).attackPower(92).defencePower(85).life(290).species(Species.COMMON).imagePath("GiantGorilla.webp").build(),
                    Animal.builder().name("괴물지네").grade(Grade.SUPERRARE).attackPower(78).defencePower(62).life(215).species(Species.COMMON).imagePath("MonsterCentipede.webp").build(),
                    Animal.builder().name("아나콘다").grade(Grade.SUPERRARE).attackPower(88).defencePower(72).life(270).species(Species.COMMON).imagePath("Anaconda.webp").build(),
                    Animal.builder().name("꽃사슴").grade(Grade.SUPERRARE).attackPower(65).defencePower(100).life(240).species(Species.COMMON).imagePath("FlowerDeer.webp").build(),
                    Animal.builder().name("쿼카").grade(Grade.SUPERRARE).attackPower(68).defencePower(82).life(210).species(Species.COMMON).imagePath("Quokka.webp").build(),
                    Animal.builder().name("팬더").grade(Grade.SUPERRARE).attackPower(70).defencePower(90).life(260).species(Species.COMMON).imagePath("Panda.webp").build(),
                    Animal.builder().name("리자드맨").grade(Grade.UNIQUE).attackPower(125).defencePower(140).life(350).species(Species.COMMON).imagePath("LizardMan.webp").build(),
                    Animal.builder().name("만드라고라").grade(Grade.UNIQUE).attackPower(110).defencePower(123).life(398).species(Species.COMMON).imagePath("Mandrake.webp").build(),
                    Animal.builder().name("만티코어").grade(Grade.UNIQUE).attackPower(133).defencePower(133).life(333).species(Species.COMMON).imagePath("Manticore.webp").build(),
                    Animal.builder().name("네시").grade(Grade.LEGEND).attackPower(187).defencePower(177).life(450).species(Species.COMMON).imagePath("Nessie.webp").build(),
                    Animal.builder().name("바실리스크").grade(Grade.LEGEND).attackPower(195).defencePower(167).life(460).species(Species.COMMON).imagePath("Basilisk.webp").build(),
                    Animal.builder().name("나이트메어").grade(Grade.LEGEND).attackPower(165).defencePower(190).life(480).species(Species.COMMON).imagePath("Nightmare.webp").build()

        ));
        }

        User user = User.builder().id("111").password(passwordEncoder.encode("111")).build();
        userRepository.save(user);

        Animal animal = animalRepository.findById(1L).get();
        Animal animal2 = animalRepository.findById(13L).get();
        Animal animal3 = animalRepository.findById(22L).get();
        Animal animal4 = animalRepository.findById(234L).get();
        Animal animal5 = animalRepository.findById(100L).get();


        if (animalINVTRepository.findAll().isEmpty()) {
            animalINVTRepository.saveAll(List.of(
                    UserAnimal.builder()
                            .user(user).animal(animal).ownedQuantity(1).placedQuantity(1).upgrade(1).build(),
                    UserAnimal.builder()
                            .user(user).animal(animal2).ownedQuantity(1).placedQuantity(1).upgrade(1).build(),
                    UserAnimal.builder()
                            .user(user).animal(animal3).ownedQuantity(1).placedQuantity(1).upgrade(1).build(),
                    UserAnimal.builder()
                            .user(user).animal(animal4).ownedQuantity(1).placedQuantity(1).upgrade(1).build(),
                    UserAnimal.builder()
                            .user(user).animal(animal5).ownedQuantity(1).placedQuantity(1).upgrade(1).build()

            ));
        }


        return ResponseEntity.status(HttpStatus.OK)
                .body("Data saved successfully");
    }}
